- update nameTag pipe
aura-nw/aurascan pull request #2722
Opened 2023-11-30 04:18 UTC by nhphuc2411

- (fix bug export csv)

2023-11-30 04:25 UTC, nttnguyen136 requested changes

2023-11-30 04:25 UTC, nttnguyen136 commented on src/app/core/pipes/common.pipe.ts
Tách ra file riêng nhé

2023-11-30 04:25 UTC, nttnguyen136 commented on src/app/core/pipes/common.pipe.ts
> +    listNameTag = listNameTag?.length > 0 ? listNameTag : listNameTag;
Chưa đúng logic
Check lại [common.service.ts#L125)](https://github.com/aura-nw/aurascan/blob/1a8dc78f15a89be784fd5ad547b1e845fc7927e7/src/app/core/services/common.service.ts#L125)

2023-11-30 04:25 UTC, nttnguyen136 commented on src/app/core/pipes/common.pipe.ts
> +@Pipe({ name: 'getNameTag' })
Đặt lại tên

2023-11-30 08:35 UTC, mtamkg approved these changes

2023-12-01 03:53 UTC, nttnguyen136 commented
Check lại cái name của Pipe cho đúng format

2023-12-04 02:06 UTC, mtamkg approved these changes

2023-12-06 07:52 UTC, nttnguyen136 approved these changes
lgtm

2023-12-06 08:15 UTC, merged