Feature/tooltip directive
aura-nw/aurascan pull request #3055
Opened 2024-02-27 04:32 UTC by letrieuthien

2024-02-27 07:25 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +    if (!element) return;
Move lên đầu

2024-02-27 07:30 UTC, letrieuthien commented on src/app/core/directives/tooltip-customize.directive.ts
> +    if (!element) return;
done

2024-02-27 07:31 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +    if (!tooltipValue || (tooltipValue && (tooltipValue === 0 || tooltipValue === '0'))) return;
```suggestion
    if (!tooltipValue || tooltipValue == '0') return;
```

2024-02-27 07:32 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +          BigNumber(this.appTooltip.lt ?? 0.001)
```suggestion
          this.appTooltip.lt ?? 0.001
```

2024-02-27 07:33 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +      const gte = BigNumber(+this.appTooltip.priceAmount)
```suggestion
      const gte = BigNumber(this.appTooltip.priceAmount)
```

2024-02-27 07:34 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +        );
```suggestion
      const gte = BigNumber(this.appTooltip.priceAmount)
        .multipliedBy(this.appTooltip.multipliedBy ?? 1).gte(1000000);
      const lt = BigNumber(this.appTooltip.priceAmount)
        .multipliedBy(this.appTooltip.multipliedBy ?? 1).lt(
          this.appTooltip.lt ?? 0.001
        );
```

2024-02-27 07:39 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +      element.addEventListener('mouseenter', (_) => {
Chưa thấy có removeEventListener

2024-02-27 09:37 UTC, nttnguyen136 requested changes
Revert name-tag

2024-02-28 06:51 UTC, nttnguyen136 requested changes
Không sửa các `class`, file liên quan đến tooltip cũ đang sử dụng, ảnh hưởng đến tooltip đang xài. Tạo mới để sử dụng. Khi nào apply hết các trang rồi mới xóa

2024-02-28 06:51 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +  }
```suggestion

```

2024-02-28 06:51 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +    let tooltipY = elementObj.top - (tooltipObj.height + 16);
Chỗ này tại sao lại cộng `16`  -> Tạo cái biến + comment code để sau dễ update
```suggestion
    const offset = 16; // Update name
    const elementBounding = element.getBoundingClientRect();
    const tooltipBounding = tooltipParent.getBoundingClientRect();
    const marginTopValue = elementObj.top - (tooltipObj.height + offset );
```

2024-02-28 06:51 UTC, nttnguyen136 commented on src/app/core/directives/tooltip-customize.directive.ts
> +        tooltipParent.style.transform = 'translate(calc(-100% - 32px), -2px)';
Comment công thức

2024-02-28 06:51 UTC, nttnguyen136 commented on src/app/core/services/common.service.ts
> +    }
```suggestion
    const offset = ((el) => {
      const rect = el.getBoundingClientRect();
      return {
        left: rect.left + window.scrollX + rect.width / 2,
        top: rect.top,
      };
    })(parent);
    if (tooltip) {
      tooltip.style.top = offset.top + 'px';
      tooltip.style.left = offset.left + 'px';
    }
```

2024-03-04 07:24 UTC, nhphuc2411 approved these changes

2024-03-04 07:27 UTC, nttnguyen136 approved these changes

2024-03-04 07:27 UTC, merged